### ISSUE TITLE
不支持mac os环境吗？

### ISSUE THREAD

**Issue by lenliu2016** [paketo-buildpacks/graalvm#107]
我的开发环境是mac os ,当运行：
```
./mvnw -Dmaven.test.skip=true spring-boot:build-image
```
![image](https://user-images.githubusercontent.com/22441598/131211017-d69e5899-d7dd-4da2-b3d4-19621b81dfdd.png)
红色方框内应该为“graalvm-ce-java11-darwin-amd64-21.2.0.tar.gz”。

**Comment by dmikusa-pivotal** [comment]
Buildpacks run in Linux containers. Even if your host OS is Mac or Windows. The buildpack will execute inside of a Linux Docker container. That's why it downloads Linux versions of GraalVM.

You can see the specific details about the Linux container in which the buildpacks will run by looking at the builder that you're using. Run `pack builder inspect`. It will show you the details for that builder.

```
> pack builder inspect paketobuildpacks/builder:base
Inspecting default builder: paketobuildpacks/builder:base

REMOTE:

Description: Ubuntu bionic base image with buildpacks for Java, .NET Core, NodeJS, Go, Ruby, NGINX and Procfile

Created By:
  Name: Pack CLI
  Version: 0.20.0+git-66a4f32.build-2668

Trusted: Yes

Stack:
  ID: io.buildpacks.stacks.bionic

Lifecycle:
  Version: 0.11.4
  Buildpack APIs:
    Deprecated: (none)
    Supported: 0.2, 0.3, 0.4, 0.5, 0.6
  Platform APIs:
    Deprecated: (none)
    Supported: 0.3, 0.4, 0.5, 0.6

Run Images:
  index.docker.io/paketobuildpacks/run:base-cnb
  gcr.io/paketo-buildpacks/run:base-cnb
...
```
