### ISSUE TITLE
How to use different GraalVM version(aarch64)?

### ISSUE THREAD

**Issue by rodrigorodrigues** [paketo-buildpacks/graalvm#65]
Hi,

I'm using Spring Native and was wondering if there's some way to pointing to a different GraalVM version(aarch64).

Pom.xml
```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<image>
			<builder>paketobuildpacks/builder:tiny</builder>
			<env>
				<BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
			</env>
		</image>
	</configuration>
</plugin>
```

**Comment by ekcasey** [comment]
Hey @rodrigorodrigues, 

Currently we only support the latest version of GraalVM, for JVM versions 8 and 11. So you can set `BP_JVM_VERSION=8` to get `graalvm-ce-java8-linux-amd64-21.0.0.2.tar.gz` instead of `graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz` but there is no way to get  `native-image-installable-svm-java11-linux-amd64-21.0.0.jar` without downgrading to an [older buildpack](https://github.com/paketo-buildpacks/graalvm/releases/tag/v5.0.0).

In the future we intend to add concurrent support for the latest minor/patch in the two latest major GraalVM version lines. Users will be able to use an environment variable `BP_GRAALVM_VERSION` set set the GraalVM version. For example, even after the next major version of GraalVM is release, you will be able to set `BP_JVM_VERSION=8` + `BP_GRAALVM_VERSION=21.*` to get `graalvm-ce-java8-linux-amd64-21.0.0.2.tar.gz`.

However, none of these changes will allow you to pull the experimental `aarch64` versions of GraalVM. Paketo does not currently offer ARM stack images these version of the `aarch64` versions of GraalVM would fail on the existing [paketo base stack images](https://paketo.io/docs/stacks/#base).

**Comment by rodrigorodrigues** [comment]
Thanks @fg-j  and @ekcasey for your great explanation.
