### ISSUE TITLE
Support Static / `FROM scratch`

### ISSUE THREAD

**Issue by jamesward** [paketo-buildpacks/graalvm#73]
It'd be great if there was a way for this buildpack to support static native images so that the run image can be `scratch`.

Bonus points if the created native application can optionally be packed with `upx`.

Here is an example `Dockerfile` that does all this:
https://github.com/jamesward/comparing-docker-methods/blob/graalvm/Dockerfile

**Comment by dmikusa-pivotal** [comment]
>Bonus points if the created native application can optionally be packed with upx.

There is an issue you can follow for this one: https://github.com/paketo-buildpacks/native-image/issues/59. I'm hoping to have it done shortly.

>It'd be great if there was a way for this buildpack to support static native images so that the run image can be scratch.

I believe that Spring Boot uses the [tiny builder](https://github.com/paketo-buildpacks/tiny-builder) by default which on my machine looks to be about 20M, so should produce images where the size is basically 20M + your native image binary size. Are you seeing something different? 

If it's just about size, I can't say this will be very high on our priority list, given that the current tiny image is as the name implies pretty tiny. If there is a use case that this opens up, besides just having a slightly smaller image, please let me know. We definitely want to unlock more use cases so that could impact priority. I also wouldn't be opposed to a PR for this, if it's something you'd like to contribute. Happy to help with that process.

**Comment by jamesward** [comment]
Thanks for the quick response!

I am using `paketobuildpacks/builder:tiny` and you're right that it is only a 17MB run image.  So that isn't too bad.  My Spring app on the other hand is 90MB so seems like the upx stuff might be the best way to improve size.

I do really like having `FROM scratch` container images for their simplicity.  But understand that it isn't really necessary.
